# Generated by Django 3.2.9 on 2022-07-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0002_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='streaming',
        ),
    ]
