# Generated by Django 3.2.9 on 2022-07-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0004_auto_20220705_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
