# Generated by Django 3.2.9 on 2022-07-05 05:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='watchlist',
            field=django_mysql.models.ListTextField(models.IntegerField(), default='', size=None),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
