# Generated by Django 3.2.9 on 2022-07-05 06:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0007_auto_20220705_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='watchlist',
            field=django_mysql.models.ListTextField(models.CharField(max_length=7), default='', size=None),
        ),
    ]
