# Generated by Django 3.2.9 on 2022-07-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0008_alter_users_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='users',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlistItems', to='perfectPick.Post'),
        ),
    ]
