# Generated by Django 3.2.9 on 2022-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0009_auto_20220705_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='users',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlistItems', to='perfectPick.Integer'),
        ),
    ]
