# Generated by Django 3.2.9 on 2022-07-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0011_users_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='Integer',
        ),
    ]
