# Generated by Django 3.2.9 on 2022-07-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0013_auto_20220705_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integer',
            name='image',
        ),
    ]
