# Generated by Django 3.2.9 on 2022-07-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfectPick', '0016_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
